Create bios program

diff --git a/bin/ca65 b/bin/ca65
--- a/bin/ca65
+++ b/bin/ca65
@@ -1,16 +1,49 @@
 #!/usr/bin/env bash
 set -euo pipefail
 
-function local_path()
-{
-    echo "$(dirname "$0")"/"$1"
-}
+source "$(dirname "$0")"/lib
 
 function main()
 {
+    if [ "$#" -ne 1 ]; then
+        echo "error: missing file to assemble"
+        echo "usage: $(basename "$0") FILE"
+        exit 1
+    fi
+    local assembly_file="$1"
+
+    local output_dir
+    output_dir="$(lib_output_dir)"
+
+    local root_name
+    root_name="$(lib_root_name "${assembly_file}")"
+
+    local object_file
+    object_file="${output_dir}/${root_name}.o"
+
+    # Assemble
     ca65 \
-        -I "$(local_path ../ca65-includes)" \
-        "$@"
+        --include-dir "$(lib_local_path ../ca65-includes)" \
+        -o "${object_file}" \
+        "${assembly_file}"
+
+    local config_file
+    config_file="$(dirname "${assembly_file}")/${root_name}.cfg"
+
+    local ld_config_args=()
+    if [ -f "${config_file}" ]; then
+        ld_config_args+=(-C "${config_file}")
+    fi
+
+    local symbol_file
+    symbol_file="${output_dir}/${root_name}.sym"
+
+    # Link
+    ld65 \
+        -o "${output_dir}/rom.bin" \
+        "${ld_config_args[@]}" \
+        -Ln "${symbol_file}" \
+        "${object_file}"
 }
 
 main "$@"
